triggers:
- envs: []
  last_enabled_at: 2024-04-17 17:13:07.894330+00:00
  name: API
  pipeline_uuid: integracao_apps
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-04-17 17:12:00
  status: active
  variables: {}
